name: KDFramework
version: '${project.version}'
main: io.github.deechtezeeuw.kdframework.KDFramework
api-version: 1.12
authors: [ DeZeeuw, 5lutty ]
description: KingdomFramework by DeZeeuw and 5lutty
softdepend: [PlaceholderAPI, WorldGuard, WorldEdit]
commands:
  kingdom:
    usage: /<command>
    description: Command to use framework commands
    aliases:
      - k
permissions:
  k.reload:
    default: op
    description: Used to reload the configuration