name: KDFramework
version: '${project.version}'
main: io.github.deechtezeeuw.kdframework.KDFramework
api-version: 1.12
authors: [ DeZeeuw, 5lutty ]
description: Kingdom framework plugin not for old kingdom
softdepend: [PlaceholderAPI]
commands:
  kingdom:
    usage: /<command>
    description: Command to use framework commands
    aliases:
      - k
permissions:
  k.reload:
    default: op
    description: Used to reload the configuration